services:
  frontend:
    image: marketplace-frontend:latest
    container_name: frontend
    volumes:
      - ./:/app
      - /app/node_modules
      - frontend-logs:/app/logs
    environment:
      - API_URL=${API_URL}
    ports:
      - "8080:8080"
    command: npm run dev

volumes:
  frontend-logs: {}