services:
  frontend:
    image: marketplace-frontend:latest
    container_name: frontend
    restart: always
    env_file: ../.env
    volumes:
      - ./:/app
      - /app/node_modules
      - frontend-logs:/app/logs
    ports:
      - ${FRONTEND_PORT}:8080

volumes:
  frontend-logs: {}