services:
  postgres:
    extends:
      file: ./backend/docker-compose.yml
      service: postgres

  redis:
    extends:
      file: ./backend/docker-compose.yml
      service: redis

  celery-worker:
    extends:
      file: ./backend/docker-compose.yml
      service: celery-worker
    depends_on:
      backend:
        condition: service_healthy

  celery-beat:
    extends:
      file: ./backend/docker-compose.yml
      service: celery-beat
    depends_on:
      backend:
        condition: service_healthy

  backend:
    extends:
      file: ./backend/docker-compose.yml
      service: backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend
    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data: { }
  redis_data: { }
  logs: { }
