services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/database
    healthcheck:
      test: [ "CMD-SHELL", "psql -U ${POSTGRES_USER} -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    image: marketplace-backend:latest
    container_name: backend
    env_file: ../.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${DJANGO_PORT}"
    ports:
      - ${DJANGO_PORT}:8000
    volumes:
      - ./:/code/
      - backend-logs:/var/log/backend
    restart: always

volumes:
  postgres-data: { }
  postgres-logs: { }
  backend-logs: { }
  redis-data: { }
