services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h postgres -p 5432" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/database

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data

  backend:
    image: marketplace-backend:latest
    container_name: backend
    env_file: ../.env
    restart: always
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - ${DJANGO_PORT}:8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./:/code/
      - backend-logs:/var/log/backend

volumes:
  postgres-data: { }
  postgres-logs: { }
  backend-logs: { }
  redis-data: { }
