name: Ensure pull request to branch "main" only from branch "develop"

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Check if PR is from develop
      run: |
        if [ "${{ github.head_ref }}" != "develop" ]; then
          echo "Pull requests to main branch can only be merged from develop branch."
          exit 1
        fi
